### ISSUE TITLE
[FEAT] ci/cd binary package artifacts should be build and published

### ISSUE THREAD

**Issue by sassman** [steganogram/stegano-rs#5]
When building a new tag, binary packages should be generated and attached to the github releases page.

**Comment by sassman** [comment]
This depends on #11 and must be tackled after.

**Comment by tunnckoCore** [comment]
Waiting. :) 

Seems like a cool project and definitely more maintained than the `steghide` which is since 2003.

I'm trying to get it on openSUSE Thumbleweed. For some reason compiling it with rust fails (with `linker 'cc' not found`), but it can be due to my read-only filesystem. Anyway, i'm reinstalling it soon so we we'll see.

**Comment by sassman** [comment]
Hey @tunnckoCore ,

Thanks for the feedback.
I believe one of the dependencies needs gcc in order to compile.

Try to install gcc and then retry. If it woks I have to update the docs to make that more obvious.

**Comment by sassman** [comment]
PS: there is a snap that you can also install and use on open suse (see the readme). As an alternative to building from source.

**Comment by tunnckoCore** [comment]
Ah thanks, I'll try.

I've seen the support of snap, the thing is i like to stick to the OS original package manager (on any os).

**Comment by tunnckoCore** [comment]
Yep. Seems to like it. Compiled.

**Comment by sassman** [comment]
> I've seen the support of snap, the thing is i like to stick to the OS original package manager (on any os).

So would you only consider RPMs or would you be open to an AppImage binary as well? I'm asking because somebody suggested AppImage on #15 

So would be happy to get more feedback in this regard.

**Comment by tunnckoCore** [comment]
Don't use AppImages and don't like the idea very much. I'm for all kind of binaries and packages. A deb, rpm and aur is enough.
